#!/usr/bin/env python

from setuptools import setup, find_packages

setup(name='test_pip',
      version='None',
      description='Autogenerated Python Avro Package',
      author='None',
      packages=find_packages(),
      include_package_data=True
)
