#!/bin/sh

docker compose up

# Creating the user admin (super user)
# The first user needs to be created using the zookeeper connection (bootstrapping process)
docker compose exec kafka kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[password=admin-secret],SCRAM-SHA-512=[password=admin-secret]' --entity-type users --entity-name admin

# All additional users can be created using the broker connection
docker compose exec kafka kafka-configs --bootstrap-server kafka:9093 --alter --add-config 'SCRAM-SHA-256=[password=kafka-secret],SCRAM-SHA-512=[password=kafka-secret]' --entity-type users --entity-name kafka --command-config /tmp/admin.properties
docker compose exec kafka kafka-configs --bootstrap-server kafka:9093 --alter --add-config 'SCRAM-SHA-256=[password=producer-secret],SCRAM-SHA-512=[password=producer-secret]' --entity-type users --entity-name producer --command-config /tmp/admin.properties
docker compose exec kafka kafka-configs --bootstrap-server kafka:9093 --alter --add-config 'SCRAM-SHA-256=[password=consumer-secret],SCRAM-SHA-512=[password=consumer-secret]' --entity-type users --entity-name consumer --command-config /tmp/admin.properties

echo "Example configuration:"
echo "-> kafka console-producer --broker-list localhost:9093 --producer.config producer.properties --topic t_raw"
echo "-> kafka console-consumer --bootstrap-server localhost:9093 --consumer.config consumer.properties --topic test --from-beginning"
echo "-> docker compose exec kafka kafka-console-consumer --bootstrap-server kafka:9093 --consumer.config /tmp/admin.properties --topic t_raw --from-beginning"
echo "-> docker compose exec kafka kafka-console-consumer --bootstrap-server kafka:9093 --consumer.config /tmp/admin.properties --topic t_cfp --from-beginning"

#
## Schema registry
#
docker compose logs schema-registry | grep "Server started, listening for requests"
while (( $? == 1 ))
do
    sleep 1
    echo "Waiting for schema registry to be started ..."
    docker compose logs schema-registry | grep "Server started, listening for requests"
done

docker compose exec schema-registry sr-acl-cli --config /etc/schema-registry/schema-registry.properties --add -s '*' -p read -o SUBJECT_READ
docker compose exec schema-registry sr-acl-cli --config /etc/schema-registry/schema-registry.properties --add -s '*' -p write -o SUBJECT_WRITE
docker compose exec schema-registry sr-acl-cli --config /etc/schema-registry/schema-registry.properties --add -s '*' -p admin -o '*'

echo "Schema Registry is listening on http://localhost:8089"
echo "-> user:password  |  description"
echo "-> _____________"
echo "-> read:read    |  Global read access"
echo "-> write:write  |  Global write access"
echo "-> admin:admin  |  Global admin access"

